apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    app: {{ include "microservice.name" . }} 
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics 
      port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ include "microservice.name" . }}
